project:
  type: website
  output-dir: docs
  render:
    - "*.qmd" 

website:
  title: "lynma01.github.io"
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - href: posts/lynma01.github.io.qmd
        text: Home

execute: 
  cache: true

format:
  html:
    # html themes from bootswatch
    theme:
      light: litera
      dark:  cyborg
    # text formatting for table of contents, chapters, etc.
    toc: true
    number-sections: true    
    crossref:
      chapters: true
      labels: roman
      subref-labels: roman
    # for dealing with source code
    code-tools:
      source: true
      toggle: false
      caption: none
    code-line-numbers: true
    # for Mermaid digrams and other extensions
    mermaid:
      theme: forest
    filters:
      - nutshell