[tool.poetry]
name = "lynma01.github.io"
version = "0.1.0"
description = ""
authors = ["lynma01 <lynma01@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.5.1"
duckdb = "^0.5.1"
numpy = "^1.23.4"
matplotlib = "^3.6.2"
altair = "^4.2.0"
ipykernel = "^6.17.1"
cogdb = "^3.0.2"
Faker = "^15.3.2"
dbt-duckdb = "^1.3.2"
openpyxl = "^3.0.10"
bokeh = "^3.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
