---
title: Space Bureacrat Series Planning 
author:
  - name: Matthew Lyn
    url: https://lynma01.github.io
title-block-banner: true
date-format: short
number-sections: true
toc: true
draft: true
---
# README
___
This is a planning document for the Space Bureacrat series. It's going to outline all the different episodes/case-studies within the series. Might also be good to do some character/narrative arcs in here. Not really sure yet.

# Synopsis:
___
The year is 2140 and humanity is now doing its thing amongst the stars (fucking shit up). You're a young technocrat on the rise within the Department of Social Wellbeing & Economic Security (pronounced "Dee-Swiz"). 

As is tradition, you're posted to hell-hole planets where if the fauna doesn't get you the people will - all the while cleaning-up messes, alleviating self-inflicted suffering, and finding the socially-optimum amount of inequallity for every government intervention.

# Problem Topics:
___
Many of these problems will run the gammet of disciplines:
    - Process Science & Operations Research
    - Behavioral Economics
    - Chemical Engineering
    - Environmental Sciences

