---
title: Process Mining in Space
draft: true
---

# Summary
[ProcesMining.org](http://www.processmining.org/story/production.html) is an analytical field dedicated to extracting performance measurements from event logs. Key metrics are usually related to things like: "how quickly is this workstation completing its jobs?", or conversely, "where are the bottle-necks within our business-processes?".

Self-described as "applied data science", Process Mining is a concrete and self-evidently useful application of data-science to create business value. Pioneered by Dutch computer scientist [Wil van der Aalst](http://www.padsweb.rwth-aachen.de/wvdaalst/), the field is defined by an extremely tight focus industry problems rather than Operations Research style academic-publishing.

[What Process Mining Is, and Why Companies Should Do It](https://hbr.org/2019/04/what-process-mining-is-and-why-companies-should-do-it).

For this article, we're going to use [pm4py](https://pm4py.fit.fraunhofer.de) to analyze a randomly generated event-log and to create a performance management report for decision-makers.