---
title: Business as Code
draft: true
---

# Summary:
Every facet of a business can be represented as data: finance, marketing, operations, and HR are all supported by Enterprise Resource Software whose primary purpose is organizing and storing that data. However, the transformation of data into insight is only understood by a fraction of the working population (analytics engineers), and is also concentrated among certain industries.

Therefore, given those constrains, it's in the interest of every client and analytics professional to be as data-savvy as possible. Lest we risk the exorbitant costs of wasted work-hours and/or cloud-storage/computation.  

There’s three types of business jobs: writing data, informing other people about the data, or building systems which process data.

# This article is about:
1. How rigorous thinking, not familiarity with programming languages or tools, is what makes analytics projects and products *successful*.
  - But what makes business analytics *possible* and *manageable* is programming languages and tools. 
2. Because analytics professionals are beholden to their client(s), they must be intimately familiar with their domain.
  - But the professional is there to research poorly or imperfectly understood problems, and is thus the domain-expert at the cutting edge. 

# Don't Just Do Something, Think About It:
> Because if you don't know where you're going, any direction will get you there.

If you can imagine for a moment having perfect recollection, masterful split-second decision-making, and the commanding ability to organize and measure the productive-capacity of legions of professionals- congratulations, you can visualize Information Technology's most mundane powers.

Which begs the question: if these promises are possible (and they are), then what's the primary obstacle to possessing them for oneself?

The simple answer is that many clients and professionals don't concretely understand what they need to remember, what information is critical to their decision-making, or what the problem is that they need legions of people to solve. Without the prerequisite critical thinking and decision-making, there's no amount of engineering which can substitute. 

